import com.android.build.api.dsl.LibraryExtension
import com.android.build.gradle.internal.tasks.factory.dependsOn
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// Module :library
plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose.compiler)
    alias(libs.plugins.builtin.kotlin)
    alias(libs.plugins.legacy.kapt)
    alias(libs.plugins.dokka.html)
    alias(libs.plugins.dokka.javadoc)
    id("maven-publish")
}

base {
    archivesName = "colorpicker_compose_${libs.versions.app.version.name.get()}"
}

kotlin {
    jvmToolchain(17)
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

composeCompiler {
    reportsDestination = layout.buildDirectory.dir("compose_compiler")
}

configure<LibraryExtension> {
    namespace = "io.syslogic.colorpicker.compose"
    compileSdk = Integer.parseInt(libs.versions.android.compile.sdk.get())

    defaultConfig {
        minSdk = Integer.parseInt(libs.versions.android.min.sdk.get())
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles(rootProject.file("consumer.pro").absolutePath)
    }

    sourceSets {
        getByName("main") {
            java.directories.add("src/main/java")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
        dataBinding = true
        compose = true
    }

    buildTypes {
        debug {
            // it breaks the data-binding, e.g. when running ./gradlew :library:publishToMavenLocal
            enableAndroidTestCoverage = false
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = false
        }
    }

    lint {
        lintConfig = rootProject.file("lint.xml")
        checkAllWarnings = true
        warningsAsErrors = true
        abortOnError = false
        showAll = false

        // TODO: Cannot invoke "org.jetbrains.uast.kotlin.KotlinUastResolveProviderService
        //  .getBindingContext(org.jetbrains.kotlin.psi.KtElement)" because "service" is null.
        disable += "MutableCollectionMutableState"
        disable += "AutoboxingStateCreation"
    }

    packaging {
        resources.pickFirsts.add("META-INF/AL2.0")
        resources.pickFirsts.add("META-INF/LGPL2.1")
        jniLibs.keepDebugSymbols.add("**/libandroidx.graphics.path.so")
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {

    implementation(libs.kotlin.stdlib)
    implementation(libs.material.design)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.preference.ktx)

    // https://mvnrepository.com/artifact/androidx.compose
    // https://developer.android.com/jetpack/compose/tooling#bom
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.bundles.androidx.compose.lib)

    /* Composable Preview */
    debugImplementation(libs.bundles.androidx.compose.tooling)

    /* Dokka Android Documentation Plugin */
    dokkaPlugin(libs.dokka.android.documentation.plugin)
}

// Dokka generation
dokka {

    dokkaSourceSets.create("main") {

        val sdkComponents = androidComponents::sdkComponents.get()
        val sdkDirectory: Directory? = sdkComponents.sdkDirectory.get()
        val compileSdk = project.extensions.getByType<LibraryExtension>().compileSdk

        sourceRoots.from(
            files(File("${sdkDirectory}/platforms/${compileSdk}/android.jar")),
            "${projectDir.absolutePath}/src/main/java"
        )

        sourceLink {
            localDirectory.set(file("${projectDir.absolutePath}/src/main/java"))
            remoteUrl("https://github.com/syslogic/androidx-colorpicker/tree/master/compose/src/main/java")
            remoteLineSuffix.set("#L")
        }
    }

    dokkaSourceSets.configureEach {

        enableJdkDocumentationLink.set(true)
        enableKotlinStdLibDocumentationLink.set(true)
        enableAndroidDocumentationLink.set(true)
        jdkVersion.set(17)

        dokkaPublications.javadoc {
            moduleName.set(project.name)
            moduleVersion.set(project.version.toString())
            outputDirectory.set(layout.buildDirectory.dir("dokka/javadoc"))
        }
        dokkaPublications.html {
            moduleName.set(project.name)
            moduleVersion.set(project.version.toString())
            outputDirectory.set(layout.buildDirectory.dir("dokka/html"))
        }
    }
}

val dokkaGenerateJavadocJar by tasks.registering(Jar::class) {
    group = "dokka"
    dependsOn(tasks.dokkaGeneratePublicationJavadoc)
    from(tasks.dokkaGeneratePublicationJavadoc.flatMap { it.outputDirectory })
    archiveClassifier.set("javadoc")
    description = "Assembles a JAR containing the Javadoc-style documentation generated by Dokka."
}

val dokkaGenerateHtmlJar by tasks.registering(Jar::class) {
    group = "dokka"
    dependsOn(tasks.dokkaGeneratePublicationHtml)
    from(tasks.dokkaGeneratePublicationHtml.flatMap { it.outputDirectory })
    archiveClassifier.set("html-docs")
    description = "Assembles a JAR containing the HTML documentation generated by Dokka."
}

val dokkaCleanJavadoc by tasks.registering(Delete::class) {
    group = "dokka"
    delete = setOf(project.file("build/dokka/javadoc"))
    description = "It removes the documentation generated by Dokka."
}

val dokkaCleanHtml by tasks.registering(Delete::class) {
    group = "dokka"
    delete = setOf(project.file("build/dokka/html"))
    description = "It removes the documentation generated by Dokka."
}

tasks.dokkaGeneratePublicationJavadoc.dependsOn(dokkaCleanJavadoc)
tasks.dokkaGeneratePublicationHtml.dependsOn(dokkaCleanHtml)

val dokkaClean by tasks.registering {
    group = "dokka"
    dependsOn(dokkaCleanJavadoc, dokkaCleanHtml)
}

val sourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
    from(project.file("src/main/java"))
}

// Gradle 9.1 deprecation fix
configurations {
    @Suppress("UnstableApiUsage")
    consumable("jars") {
        outgoing.artifact(dokkaGenerateJavadocJar)
        outgoing.artifact(sourcesJar)
    }
}

tasks.named("assemble") {
    dependsOn(dokkaGenerateJavadocJar)
    dependsOn(sourcesJar)
}

group   = "io.syslogic"
version = libs.versions.app.version.name.get()

afterEvaluate {
    publishing {
        publications {
            register("release", MavenPublication::class) {
                from(components.getByName("release"))
                groupId = group as String?
                artifactId = "colorpicker-compose"
                version = libs.versions.app.version.name.get()
                pom {
                    name = "Color Picker Compose"
                    description = "A simple color-picker library for Android"
                    url = "https://github.com/syslogic/androidx-colorpicker"
                    scm {
                        connection = "scm:git:git://github.com/syslogic/androidx-colorpicker.git"
                        developerConnection = "scm:git:ssh://github.com/syslogic/androidx-colorpicker.git"
                        url = "https://github.com/syslogic/androidx-colorpicker/"
                    }
                    developers {
                        developer {
                            // name = githubDev
                            // email = githubEmail
                            // id = githubHandle
                        }
                    }
                    licenses {
                        license {
                            name = "MIT License"
                            url = "http://www.opensource.org/licenses/mit-license.php"
                        }
                    }
                }
            }
        }
    }
}
