name: 🤖 Android CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '.run/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '.run/**'

env:
  JDK_URL: https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
  JDK_FILE: ./amazon-corretto-17-x64-linux-jdk.tar.gz

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Get latest Corretto URL
        id: get-latest-corretto-url
        run: echo "{URL}={$(curl -LIs -o /dev/null -w %{url_effective} $JDK_URL)}" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: corretto-cache
        name: Restore Corretto
        with:
          path: $JDK_FILE
          key:  ${{ runner.os }}-corretto-${{ $GITHUB_OUTPUT.URL }}

      - name: Download AWS Corretto
        if: steps.corretto-cache.outputs.cache-hit != 'true'
        run: wget ${{ steps.get-latest-corretto-url.outputs.URL }}

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: '17'
          architecture: x64
          jdkFile: $JDK_FILE

      - name: 🔢 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔨 Build with Gradle
        run: ./gradlew :library:assembleRelease
