name: 🤖 Android CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .run/**
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .run/**

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: ☕ set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 🔢 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔨 Build with Gradle
        run: ./gradlew :library:assembleRelease
