name: 🤖 Android CI

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'
    paths-ignore:
      - 'LICENSE'
      - '**/README.md'
      - 'screenshots/**'
      - '.github/FUNDING.yml'
      - '.gitignore'
      - '.idea/**'
      - '.run/**'

  pull_request:
    branches: [ master ]
    tags:
      - '*.*.*'
    paths-ignore:
      - 'LICENSE'
      - '**/README.md'
      - 'screenshots/**'
      - '.github/FUNDING.yml'
      - '.gitignore'
      - '.idea/**'
      - '.run/**'

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      #  https://github.com/actions/setup-java
      - name: ☕ Set up AWS Corretto JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'
          architecture: x64

      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # GITHUB_REF may be "master".
      - name: 🔢 Set version tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: 🔢 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔨 Build with Gradle
        env:
          VERSION_TAG: ${{ steps.vars.outputs.tag }}
        run: ./gradlew :library:assembleRelease

      # https://github.com/actions/upload-artifact
      - name: 📦 Retain Artifacts (Release AAR)
        id: retain-release-aar
        uses: actions/upload-artifact@v4
        with:
          name: androidx-colorpicker-aar
          path: ./library/build/outputs/aar/colorpicker_*-release.aar
          retention-days: 14
